project:
  type: book
  output-dir: docs
  execute-dir: project
  pre-render: "R/_insert-chapter-yaml.R"
  post-render:
  - "R/_restore-dirs.R"
  - "R/_restore-yaml.R"
  
book:
  title: "Quarton perusteet"
  author: "Oliver Saal"
  date: last-modified
  chapters:
  - index.qmd
  
bibliography: references.bib
lang: fi

format:
  html:
    theme: superhero
    
execute:
  freeze: true

